apiVersion: v1
kind: Pod
metadata:
  name: demo-pod2
  labels:
    name: demo-pod2
spec:
  schedulerName: my-scheduler
  containers:
  - name: demo-pod2
    image: nginx:1.14.2
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
        falcon.com/gpu: 2
      limits:
        memory: "128Mi"
        cpu: "500m"
        falcon.com/gpu: 2
    ports:
      - containerPort: 80
