apiVersion: v1
kind: Pod
metadata:
  name: falcon-pod3
  labels:
    name: falcon-pod3
spec:
  schedulerName: my-scheduler
  containers:
  - name: falcon-pod3
    image: nginx:1.14.2
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
        falcon.com/gpu: 9
      limits:
        memory: "128Mi"
        cpu: "500m"
        falcon.com/gpu: 9
    ports:
      - containerPort: 80
