apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  schedulerName: my-scheduler
  containers:
  - name: demo-pod
    image: "nginx:1.14.2"
    command: ['sh', '-c', 'echo "start" && sleep 180']
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
        falcon.com/gpu: 1
      limits:
        memory: "128Mi"
        cpu: "500m"
        falcon.com/gpu: 1
    ports:
      - containerPort: 80
  restartPolicy: OnFailure
