# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: my-scheduler 
  image: irenetht/my-scheduler:latest 
  replicaCount: 1
  leaderElect: false

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  enabled: ["FalconResources"]

pluginConfig:
  - name: NodeResourcesFit
    args:
      ignoredResourceGroups: ["falcon.com"]