apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reconfig-daemon
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: reconfig-daemon
  template:
    metadata:
      labels:
        name: reconfig-daemon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      serviceAccountName: reconfig-daemon
      containers:
      - name: reconfig-daemon
        image: irenetht/reconfig-daemon:latest
        imagePullPolicy: Never      
        volumeMounts:
            - name: api-config
              mountPath: /etc/kubernetes
              readOnly: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
      volumes:
      - name: api-config
        configMap:
          name: api-config
