apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: {{ .Values.scheduler.leaderElect }}
    profiles:
    # Compose all plugins in one profile
    - schedulerName: {{ .Values.scheduler.name }}
      plugins:
        multiPoint:
          enabled:
          {{- range $.Values.plugins.enabled }}
          - name: {{ title . }}
          {{- end }}
        # preFilter:
        #   enabled:
        #   - name: "GpuPool"
        # score:
        #   enabled:
        #   - name: "GpuPool"
      #     disabled:
      #     - name: "NodeResourcesFit"
      #   filter:
      #     disabled: "NodeResourcesFit"
      {{- if $.Values.pluginConfig }}
      pluginConfig: {{ toYaml $.Values.pluginConfig | nindent 6 }}
      {{- end }}
      
# IgnoredResourceGroups = nvidia.com
# kubernetes/pkg/scheduler/framework/plugins/noderesources/fit.go